# Any variable can be overridden via 'custom_config.yaml' (path set by optional environment variable).

# IDs
## Groups (valid values must be defined for the bot to function)
dev_chat_id: 0
main_group_id: 0
approve_group_id: 0
## Topics (optional, used if truthy values are defined)
requests_appr_tid: 0 # Join requests messages.
responses_appr_tid: 0 # Responses to bot messages.

# Paths
state_path: "bot_data.pickle"
log_path: "log.log"

# Options
expiration_minutes: 1440 # 1 day

# Mensajes
welcome_msg: |
  Hola! Soy el bot que gestiona los ingresos en el grupo de OpenStreetMap Argentina. Antes de aceptar tu solicitud, por favor contame:

  👉 de dónde sos
  👉 cómo conociste el grupo
  👉 si usás OSM y cuál es tu usuario (si ya lo tenés)

  Es para asegurarme de que tenés un interés genuino en nuestra comunidad.
  Si no respondés en un día, rechazaré la solicitud (pero podés volver a pedir ingreso después). Gracias!
disconnected_msg: |
  No veo que tengas una solicitud de unión activa.
  https://t.me/osm_ar
attachment_msg: "No puedo leer adjuntos :-("
sent_msg: "Mensaje enviado al grupo de aprobación de ingresos."
expired_msg: |
  Tu solicitud de ingreso expiró porque no pudimos asegurarnos de que eres humano/a.
  Puedes solicitar unirte nuevamente si todavía lo deseas.
